# BUILD STAGE
FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

# Dependencies
COPY go.mod go.sum ./
RUN go mod download

COPY . .

# Install migrate CLI
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

# Build app
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app ./cmd/api


# RUNTIME STAGE
FROM alpine:latest

WORKDIR /app

RUN apk add --no-cache ca-certificates bash

COPY --from=builder /app/app .
COPY --from=builder /go/bin/migrate /usr/local/bin/migrate
COPY --from=builder /app/internal/database/migrations ./migrations

COPY docker-entrypoint.sh .

RUN chmod +x docker-entrypoint.sh

EXPOSE 8080

ENTRYPOINT ["./docker-entrypoint.sh"]